[package]
name = "watermark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
photon-rs = "0.3.2"
photon = "0.0.0"
clap = { version = "4.1.11", features = ["derive"] }